spring:
  datasource:
    url: jdbc:h2:mem:subtly
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: subtly-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration: 86400000 # 24 hours
